language: python
python:
 - "2.7"
install:
 - pip install -r requirements.txt
script:
 - python slackback/tests/run_tests.py
after_success:
 - coverage run --source=. slackback/tests/unittests/test_webservices.py 
 - coveralls
